### ISSUE TITLE
User Settings Backend

### ISSUE THREAD

**Issue by realCalvin** [jerrylee17/casino#29]
- Be able to change username (check if it's available & also change all tables w/ the old username value)
- Change email
- Change password
- Delete account

**Comment by hsorathia** [comment]
is this going to be accessible by the user as a form in their profile?

**Comment by realCalvin** [comment]
I think it should be in something like "my settings" in the navbar (like it is rn). But, the profile could have a button to link them to the settings page if they wanna change something

**Comment by hsorathia** [comment]
oh ok sick
