### ISSUE TITLE
Check user status (banned) before logging in

### ISSUE THREAD

**Issue by realCalvin** [jerrylee17/casino#31]
- Write a query to grab a user's status--to check if they're banned or not
- If a user is banned, do not let them log in (even better, show a message saying they are banned)

Login operations are done here:
https://github.com/jerrylee17/casino/blob/master/src/Components/Auth/LoginModal.js
https://github.com/jerrylee17/casino/blob/master/backend/routes/auth.js

**Comment by hsorathia** [comment]
how can I ban a user?

**Comment by realCalvin** [comment]
import this function & pass in user as param

https://github.com/jerrylee17/casino/blob/fed9949567e9c62983a8a4bbbbcd6ac4789dbcf1/src/APIFunctions/user.js#L109

**Comment by realCalvin** [comment]
ran across error in login functionality. banned is stored as a char in our db apparently.
`if(banned)` will always be true-whether it be`if('0')` or `if('1')`. To fix this, do `if(banned === '1')`

![image](https://user-images.githubusercontent.com/35363054/79803630-32eb7680-8317-11ea-93de-12885e7e62c1.png)

**Comment by hsorathia** [comment]
bruh
