### ISSUE TITLE
Allow admin users to use the admin page

### ISSUE THREAD

**Issue by hsorathia** [jerrylee17/casino#49]
Currently we don't have a way to make a user an admin, and to access the admin website, the user needs to add /admin/ at the end of their URL. 

So, we need either:

- Initialize an admin user through SQL workbench

**OR**

- Allow user to select "this is an admin account" on the register modal

**AND**

- Add an additional link in the navbar settings drop-down that allows the user to select and navigate to the admin page if they're and admin
- Admin page should redirect a user to home page if they try to hard-code the admin link.

**Comment by realCalvin** [comment]
Fixed by #51
