### ISSUE TITLE
Create Database tables based on ER diagram

### ISSUE THREAD

**Issue by jerrylee17** [jerrylee17/casino#5]
Create the database tables based on our ER diagram.

**Comment by tiffanynn** [comment]
problems:
1.) having trouble on defining multi-valued attributes: badges, players_list
2.) how should win-loss ratio be represented?
3.) attributes for player-list?

what i accomplished (I THINK):
1.) store entity
2.) game entity

what's not done yet:
1.) the disjointed entities
2.) "invited-by" relationship
3.) "manages" relationship between admin and player

i pushed it into my branch if you want to see

**Comment by tiffanynn** [comment]
there's an error on foreign key between main user and other user-related entities
![Untitled](https://user-images.githubusercontent.com/38818071/77986018-df16e000-72ca-11ea-8040-8b608ba9deb5.png)

**Comment by realCalvin** [comment]
I think one way to fix the foreign key error is to create the tables first, and then insert the foreign key afterward.

**Comment by tiffanynn** [comment]
does that work? i'm gonna try it. i haven't added anything yet, but please give me some data to insert as well

**Comment by tiffanynn** [comment]
i added some things into the badges and player-list entities for the database. i commented out foreign keys also. lmk what you guys think, i made comments on each commit i made.
