### ISSUE TITLE
Bugfixes

### ISSUE THREAD

**Issue by hsorathia** [jerrylee17/casino#66]
A couple bugs in our website:
![image](https://user-images.githubusercontent.com/36381158/80292455-af14fe00-870b-11ea-9551-c46d2e24a116.png)

![image](https://user-images.githubusercontent.com/36381158/80292461-b63c0c00-870b-11ea-89f6-33c136a21fc7.png)

**Comment by realCalvin** [comment]
you still get the mysql bug? Also can you fix the home page so that it shows the user receiving daily credit at the top. It's currently all the way at the bottom.

https://github.com/jerrylee17/casino/blob/12bd98b35405012ee05d93ec28ce03692f86514c/src/Pages/Home/Home.js#L139

**Comment by hsorathia** [comment]
it's a different mysql error which is caused by a discrepancy in how we save usernames in tables that are not players or user. we have a maximum of 15 chars in those, but other tables like the admin table have a maximum of 10 chars allowed for a username.

also yee i gotchu
