### ISSUE TITLE
Create Game Algoriothms

### ISSUE THREAD

**Issue by farefaine** [jerrylee17/casino#7]

**Comment by jerrylee17** [comment]
Oh yeah I got this one. algorithms shouldn't be difficult.

**Comment by farefaine** [comment]
> Oh yeah I got this one. algorithms shouldn't be difficult.

@jerrylee17 
I will work on creating game algorithms as well

**Comment by jerrylee17** [comment]
Wait I'll assign this to you then @FanusArefaine
